site_name: "Rishabh Desai"
theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs: false
    - navigation.top: false
  favicon: assets/images/favicon/favicon-32x32.png

# extra_css:
#   - overrides/extra.css


